### PR TITLE
Update manage.py

### LINKED ISSUE #94: Add debug=True in debugrun in manage.py
In [manage.py](https://github.com/Abdur-rahmaanJ/shopyo/blob/master/shopyo/manage.py) we have

```python
@manager.command
def rundebug():
    app.run()
```

change `app.run()` to `app.run(debug=True, host='0.0.0.0')`

### PR DESCRIPTION
**Pull request by priyanshbalyan**
Fixes #94

### CODE REVIEW

**Comment by Abdur-rahmaanJ** [comment]
Great! Congrats on your first PR! You have twitter? I'd like to give you a shoutout!

**Comment by priyanshbalyan** [comment]
Nope. Sorry no twitter.

**Comment by Abdur-rahmaanJ** [comment]
@priyanshbalyan you are from India? You can add the Indian flag in the README.

**Comment by priyanshbalyan** [comment]
Okay

**Pull request merged**
