### PR TITLE
Added roles mechanism

### PR DESCRIPTION
**Pull request by Abdur-rahmaanJ**
## How this can be tested.
- Checkout branch `role-add`.
- To test this functionality, you will need to run migrations  using the command `python manage.py migrate`.
- You then need to upgrade your database using the command `python manage.py upgrade`.
- Login as an admin and head to the admin section. 
- You are not able to edit any user to add permission.

### CODE REVIEW

**Comment by Abdur-rahmaanJ** [comment]
roles_addition_shopyo

**Comment by Abdur-rahmaanJ** [comment]
shopyo_add_roles

**Comment by Abdur-rahmaanJ** [comment]
@arthurarty 

You will see this near merge

github_check_local

Then you will see

github_check_local_ins

**Comment by arthurarty** [comment]
@Abdur-rahmaanJ hehe sorry I meant how to add a role.

**Comment by Abdur-rahmaanJ** [comment]
@arthurarty just add a new user, roles with checkboxes will be proposed

roles modifies in config.py

**Comment by arthurarty** [comment]
@Abdur-rahmaanJ I have checked it out locally. Looks good. I have also updated the PR description to include some of the steps required to try this locally.

**Pull request merged**
