### PR TITLE
Add emoji and fix casing for Complete commands

### PR DESCRIPTION
**Pull request by anir1ghosh**

### CODE REVIEW

**Comment by Abdur-rahmaanJ** [comment]
Ok thank yo and congrats on your first PR!

**Comment by Abdur-rahmaanJ** [comment]
You have twitter? I'd like to give you a shoutout!

**Comment by anir1ghosh** [comment]
Though I'm not very active, anir1ghosh is my handle on Twitter. I really appreciate this. Thanks!

**Comment by Abdur-rahmaanJ** [comment]
Done!

**Pull request merged**
