### PR TITLE
Added emoji for Understand Shopyo

### PR DESCRIPTION
**Pull request by touqeer121**
The magnifying glass emoji indicates to take a closer look or understand.

### CODE REVIEW

**Comment by Abdur-rahmaanJ** [comment]
You have a github handle? We'd like to give you a shoutout and ... add your flag in readme if not already present

**Comment by touqeer121** [comment]
> You have a github handle? We'd like to give you a shoutout and ... add your flag in readme if not already present

Yeah, its @touqeer121 only , thanks.

**Comment by Abdur-rahmaanJ** [comment]
@touqeer121 i meant Twitter handle, sorry ^^

**Comment by touqeer121** [comment]
Oh okay, currently I'm not having one. Thanks though.

**Pull request merged**
