### PR TITLE
fix: Several of issues found on products module are fixed

### PR DESCRIPTION
**Pull request by memoglr**

### CODE REVIEW

**Comment by Abdur-rahmaanJ** [comment]
Thank You 💯

**Comment by Abdur-rahmaanJ** [comment]
Btw flag not showing!

**Comment by Abdur-rahmaanJ** [comment]
Btw i reverted your PR as we let people use the app just for inventory purposes.

**Comment by memoglr** [comment]
> Btw i reverted your PR as we let people use the app just for inventory purposes.

I'm not sure whats this means, we still want the issues?

**Comment by Abdur-rahmaanJ** [comment]
This one is a good fix: `<td>{{p.category_name}}</td>` as for other it's great but force people to specify the price. Sometimes people use the project just for inventory purposes (i.e they dont care about price)

**Comment by memoglr** [comment]
> This one is a good fix: `<td>{{p.category_name}}</td>` as for other it's great but force people to specify the price. Sometimes people use the project just for inventory purposes (i.e they dont care about price)

Ok I get it, but we are getting the price and selling_price as NULL on the DB even if a number is entered, also discontinued is always as True even if picking 'No' on the discontinued field.

**Pull request merged**
