### PR TITLE
fix: Several of issues found on products module are fixed - enhanced

### PR DESCRIPTION
**Pull request by memoglr**
Made the updates considering the inventory purposes, please take a look

### CODE REVIEW

**Comment by Abdur-rahmaanJ** [comment]
Fine! You understood it well!

**Comment by Abdur-rahmaanJ** [comment]
Btw from what country are you? The flag you added does not show up!

**Comment by memoglr** [comment]
> Btw from what country are you? The flag you added does not show up!

I'm from Mexico

**Comment by Abdur-rahmaanJ** [comment]
@memoglr you are on discord?

**Comment by memoglr** [comment]
> @memoglr you are on discord?

yep

**Comment by Abdur-rahmaanJ** [comment]
Under what name?

**Comment by memoglr** [comment]
> Under what name?

@Guillermo

**Pull request merged**
